import type { Rule } from "./types";

export const otherLangRules: Rule[] = [
  // ── Go ──
  {
    id: "go-exec-command",
    langs: ["go"],
    severity: "medium",
    category: "security",
    title: "Go shell command from input",
    roast: "exec.Command with 'sh -c' plus input is a familiar trap.",
    plain: "Running sh -c with a built string and user input can let people run their own commands.",
    fix: "Call exec.Command(name, arg1, arg2) with separate arguments. Skip the shell wrapper.",
    confidence: "low",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /exec\.Command\(\s*"(sh|bash)"\s*,\s*"-c"/,
    skipTests: true,
  },
  {
    id: "go-sql-sprintf",
    langs: ["go"],
    severity: "critical",
    category: "security",
    title: "Go SQL built with Sprintf",
    roast: "fmt.Sprintf into a query is SQL injection waiting to happen.",
    plain: "Building a SQL string with Sprintf and user input lets attackers rewrite the query.",
    fix: "Use placeholders: db.Query('SELECT * FROM users WHERE id = $1', id).",
    confidence: "medium",
    reference: "https://owasp.org/www-community/attacks/SQL_Injection",
    pattern: /(Query|Exec)\w*\(\s*fmt\.Sprintf\(/,
    skipTests: true,
  },
  {
    id: "go-tls-skip-verify",
    langs: ["go"],
    severity: "medium",
    category: "security",
    title: "TLS verification turned off",
    roast: "InsecureSkipVerify: true means 'any certificate will do'.",
    plain: "Skipping TLS checks means a fake server can pretend to be the real one and read your traffic.",
    fix: "Remove InsecureSkipVerify, or set it only in local testing behind a flag.",
    confidence: "high",
    reference: "https://cwe.mitre.org/data/definitions/295.html",
    pattern: /InsecureSkipVerify\s*:\s*true/,
    skipTests: true,
  },

  // ── Ruby ──
  {
    id: "ruby-eval",
    langs: ["ruby"],
    severity: "critical",
    category: "security",
    title: "Ruby eval on a string",
    roast: "eval in Ruby runs whatever shows up. Bold trust.",
    plain: "eval, instance_eval, and class_eval run strings as code. With user input that is remote code execution.",
    fix: "Avoid eval. Use a case statement or a method lookup for dynamic choices.",
    confidence: "medium",
    reference: "https://cwe.mitre.org/data/definitions/95.html",
    pattern: /(^|[^.\w])(eval|instance_eval|class_eval)\s*[\s(]/,
    skipTests: true,
  },
  {
    id: "ruby-system-interp",
    langs: ["ruby"],
    severity: "medium",
    category: "security",
    title: "Ruby system command with input",
    roast: "Backticks and system() with input is the old-school shell exploit.",
    plain: "Putting user input inside system() or backticks can run extra shell commands.",
    fix: "Pass arguments as a list: system('ls', path). Avoid string building.",
    confidence: "low",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /system\s*\(\s*["'][^"']*#\{|`[^`]*#\{/,
    skipTests: true,
  },

  // ── PHP ──
  {
    id: "php-eval",
    langs: ["php"],
    severity: "critical",
    category: "security",
    title: "PHP eval()",
    roast: "PHP eval is the haunted house of web security.",
    plain: "eval() runs a string as PHP. With any user input it is full code execution.",
    fix: "Remove eval. Use arrays or match() for dynamic choices.",
    confidence: "medium",
    reference: "https://cwe.mitre.org/data/definitions/95.html",
    pattern: /(^|[^.\w])eval\s*\(/,
    skipTests: true,
  },
  {
    id: "php-sql-interp",
    langs: ["php"],
    severity: "critical",
    category: "security",
    title: "PHP SQL with variables inside",
    roast: "$_GET dropped straight into a query. A classic for a reason.",
    plain: "Putting request variables directly into a SQL string is SQL injection.",
    fix: "Use prepared statements with PDO or mysqli and bind your values.",
    confidence: "medium",
    reference: "https://owasp.org/www-community/attacks/SQL_Injection",
    pattern: /(query|mysqli_query|->query)\s*\([^)]*\$_(GET|POST|REQUEST)/,
    skipTests: true,
  },

  // ── Java ──
  {
    id: "java-runtime-exec",
    langs: ["java"],
    severity: "medium",
    category: "security",
    title: "Java Runtime.exec with input",
    roast: "Runtime.exec on a built string is the textbook example.",
    plain: "Runtime.exec with a string that includes user input can run extra commands.",
    fix: "Use ProcessBuilder with a list of arguments instead of one command string.",
    confidence: "low",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /Runtime\.getRuntime\(\)\.exec\(\s*[^)]*\+/,
    skipTests: true,
  },
  {
    id: "java-sql-concat",
    langs: ["java"],
    severity: "critical",
    category: "security",
    title: "Java SQL built by string adding",
    roast: "Statement plus string adding is SQL injection in a suit.",
    plain: "Building SQL with + and user input lets attackers change the query.",
    fix: "Use PreparedStatement with ? placeholders and set the values.",
    confidence: "low",
    reference: "https://owasp.org/www-community/attacks/SQL_Injection",
    pattern: /(executeQuery|executeUpdate)\s*\(\s*"[^"]*"\s*\+/,
    skipTests: true,
  },
];
