import type { Rule } from "./types";

export const rustRules: Rule[] = [
  {
    id: "rust-unsafe-block",
    langs: ["rust"],
    severity: "medium",
    category: "memory-safety",
    title: "unsafe block in Rust",
    roast: "You turned off Rust's seatbelt on purpose. Hope you meant to.",
    plain: "An unsafe block skips Rust's memory checks. Mistakes here can cause crashes or memory bugs that Rust normally prevents.",
    fix: "Make sure every unsafe block really needs to be unsafe, keep it tiny, and write a comment explaining why it is safe. Prefer safe wrappers from crates when you can.",
    confidence: "medium",
    reference: "https://doc.rust-lang.org/nomicon/",
    pattern: /\bunsafe\s*\{/,
    skipTests: true,
  },
  {
    id: "rust-unwrap",
    langs: ["rust"],
    severity: "low",
    category: "code-quality",
    title: ".unwrap() that can crash",
    roast: "unwrap is a tiny landmine that goes off on the worst input.",
    plain: "Calling .unwrap() or .expect() crashes the whole program if the value is missing or an error. Fine in scripts, risky in a running service.",
    fix: "Handle the error with match, if let, or the ? operator so a bad case returns an error instead of crashing.",
    confidence: "low",
    reference: "https://doc.rust-lang.org/book/ch09-00-error-handling.html",
    pattern: /\.unwrap\(\)|\.expect\(/,
    skipTests: true,
  },
  {
    id: "rust-panic",
    langs: ["rust"],
    severity: "low",
    category: "code-quality",
    title: "panic!() in library code",
    roast: "panic! ends the show for everyone watching.",
    plain: "panic!() stops the program. In a server or library, one bad request can take the whole thing down.",
    fix: "Return a Result and let the caller decide what to do. Save panic for truly impossible states.",
    confidence: "low",
    reference: "https://doc.rust-lang.org/std/macro.panic.html",
    pattern: /\bpanic!\s*\(/,
    skipTests: true,
  },
  {
    id: "rust-command-injection",
    langs: ["rust"],
    severity: "medium",
    category: "security",
    title: "Shell command built with format!",
    roast: "Gluing user text into a shell command is a classic.",
    plain: "Building a command string with format! and user input can let people run their own commands.",
    fix: "Use Command::new with .arg() for each piece. Do not pass a whole string to a shell.",
    confidence: "low",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /Command::new\(\s*"(sh|bash|cmd)"\s*\)/,
    skipTests: true,
  },
  {
    id: "rust-transmute",
    langs: ["rust"],
    severity: "medium",
    category: "memory-safety",
    title: "mem::transmute used",
    roast: "transmute is the 'trust me' of type safety.",
    plain: "transmute reinterprets bytes as another type with no checks. Easy to get wrong and cause memory bugs.",
    fix: "Use safe conversions like as, From, or TryFrom. Reach for transmute only as a last resort with a clear reason.",
    confidence: "medium",
    reference: "https://doc.rust-lang.org/std/mem/fn.transmute.html",
    pattern: /mem::transmute|transmute\s*::</,
    skipTests: true,
  },
];
