import type { Rule } from "./types";

const REF = "https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_password";

// Secrets can hide in any language, so these run on "any".
export const secretRules: Rule[] = [
  {
    id: "secret-openai",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "OpenAI key sitting in the code",
    roast: "You are now paying for a stranger's chatbot. Sweet of you.",
    plain: "An OpenAI key (sk-...) is hard-coded. Anyone who reads this file can spend your money.",
    fix: "1. Make a new key at platform.openai.com/api-keys and delete this one.\n2. Move it to a .env file as OPENAI_API_KEY.\n3. Make sure .env is in .gitignore.",
    confidence: "high",
    reference: REF,
    pattern: /sk-[a-zA-Z0-9]{20,}/,
    skipTests: false,
  },
  {
    id: "secret-anthropic",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "Anthropic key sitting in the code",
    roast: "Even the safety-focused AI cannot save you from a hard-coded key.",
    plain: "An Anthropic key (sk-ant-...) is in the code. Anyone can run up your bill with it.",
    fix: "1. Rotate it at console.anthropic.com.\n2. Move it to .env as ANTHROPIC_API_KEY.\n3. Add .env to .gitignore.",
    confidence: "high",
    reference: REF,
    pattern: /sk-ant-[a-zA-Z0-9\-]{20,}/,
    skipTests: false,
  },
  {
    id: "secret-stripe-live",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "Stripe live key out in the open",
    roast: "You published the keys to your bank. Bold.",
    plain: "A live Stripe secret key is in the code. That is full access to charges, refunds, and customer data.",
    fix: "1. Roll the key now at dashboard.stripe.com/apikeys.\n2. Read it from process.env.STRIPE_SECRET_KEY instead.\n3. Never put live keys in anything the browser can see.",
    confidence: "high",
    reference: REF,
    pattern: /sk_live_[a-zA-Z0-9]{20,}/,
    skipTests: false,
  },
  {
    id: "secret-aws",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "AWS access key in the code",
    roast: "Your cloud bill is about to become someone's crypto farm.",
    plain: "An AWS access key ID is hard-coded. Paired with the secret, it opens your whole AWS account.",
    fix: "1. Turn the key off in the AWS IAM console right away.\n2. Check CloudTrail for usage you did not do.\n3. Use IAM roles or a secrets manager from now on.",
    confidence: "high",
    reference: "https://cwe.mitre.org/data/definitions/798.html",
    pattern: /AKIA[0-9A-Z]{16}/,
    skipTests: false,
  },
  {
    id: "secret-github-pat",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "GitHub token in the code",
    roast: "Someone can now push to your repos. Hope they are nice.",
    plain: "A GitHub personal access token is hard-coded. Depending on scope it can read and write your repos.",
    fix: "1. Revoke it at github.com/settings/tokens.\n2. Check recent repo activity.\n3. Use Actions secrets or env vars instead.",
    confidence: "high",
    reference: REF,
    pattern: /ghp_[a-zA-Z0-9]{36}/,
    skipTests: false,
  },
  {
    id: "secret-supabase-service",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "Supabase service_role key exposed",
    roast: "That is the master key to your whole database. And it is on the internet.",
    plain: "The Supabase service_role key skips all your security rules. Anyone with it can read or delete everything.",
    fix: "1. Rotate it in Supabase, Settings then API.\n2. This key is server-only, never ship it to the browser.\n3. Read it from an env var in server code.",
    confidence: "high",
    reference: "https://supabase.com/docs/guides/api/api-keys",
    pattern: /service_role[^"'\n]{0,20}eyJ[a-zA-Z0-9_-]{20,}/,
    skipTests: false,
  },
  {
    id: "secret-google",
    langs: ["any"],
    severity: "medium",
    category: "secrets",
    title: "Google or Firebase key in the code",
    roast: "Google knows. Now the whole repo knows too.",
    plain: "A Google or Firebase API key is hard-coded. Without restrictions it can be used by anyone.",
    fix: "1. Restrict the key in Google Cloud, APIs and Services then Credentials.\n2. Move it to an env var.\n3. Turn on app and domain limits.",
    confidence: "medium",
    reference: "https://cloud.google.com/docs/authentication/api-keys",
    pattern: /AIza[0-9A-Za-z\-_]{35}/,
    skipTests: false,
  },
  {
    id: "secret-mongo-uri",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "MongoDB connection string exposed",
    roast: "Whole database, free for anyone who scrolls this far.",
    plain: "A MongoDB connection string with a username and password is in the code.",
    fix: "1. Change the database password now in Atlas.\n2. Read it from process.env.MONGODB_URI.\n3. Check access logs for queries you did not run.",
    confidence: "high",
    reference: REF,
    pattern: /mongodb(\+srv)?:\/\/[^"'\s]{10,}/i,
    skipTests: false,
  },
  {
    id: "secret-postgres-uri",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "Postgres connection string exposed",
    roast: "SELECT everything FROM your_database WHERE oops = true.",
    plain: "A Postgres connection string with credentials is hard-coded.",
    fix: "1. Rotate the database password.\n2. Read it from process.env.DATABASE_URL.\n3. Put the database behind a pooler if you can.",
    confidence: "high",
    reference: REF,
    pattern: /postgres(?:ql)?:\/\/[^"'\s]{10,}/i,
    skipTests: false,
  },
  {
    id: "secret-private-key",
    langs: ["any"],
    severity: "critical",
    category: "secrets",
    title: "Private key pasted into the repo",
    roast: "The whole point of a private key is that it stays private.",
    plain: "A private key block is committed. This can be an SSH, TLS, or signing key.",
    fix: "1. Treat this key as burned. Generate a new one.\n2. Remove the file and add its path to .gitignore.\n3. Rotate anything that trusted the old key.",
    confidence: "high",
    reference: "https://cwe.mitre.org/data/definitions/321.html",
    pattern: /-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----/,
    skipTests: false,
  },
  {
    id: "secret-slack-webhook",
    langs: ["any"],
    severity: "medium",
    category: "secrets",
    title: "Slack or Discord webhook exposed",
    roast: "Anyone can now post in your channel. As you.",
    plain: "A chat webhook URL is hard-coded. People can send messages to your channel with it.",
    fix: "1. Delete and recreate the webhook.\n2. Store the new URL in an env var.",
    confidence: "medium",
    pattern: /https:\/\/(hooks\.slack\.com\/services|discord(?:app)?\.com\/api\/webhooks)\/[A-Za-z0-9_\-\/]+/,
    skipTests: false,
  },
  {
    id: "secret-jwt-hardcoded",
    langs: ["any"],
    severity: "medium",
    category: "secrets",
    title: "Hard-coded JWT signing secret",
    roast: "If everyone knows the secret, it is not a secret.",
    plain: "A JWT signing secret looks hard-coded. If it leaks, anyone can forge logged-in sessions.",
    fix: "1. Move the secret to an env var.\n2. Use a long random value.\n3. Rotate it and force users to log in again.",
    confidence: "low",
    reference: "https://owasp.org/www-project-web-security-testing-guide/",
    pattern: /(jwt[_-]?secret|jwtSecret)\s*[:=]\s*["'][^"']{6,}["']/i,
    skipTests: true,
  },
];
