import type { Rule } from "./types";

const SWC = "https://swcregistry.io/";

export const solidityRules: Rule[] = [
  {
    id: "sol-tx-origin",
    langs: ["solidity"],
    severity: "critical",
    category: "smart-contract",
    title: "tx.origin used for auth",
    roast: "tx.origin checks are how phishing contracts drain wallets.",
    plain: "Using tx.origin to check who is calling can be tricked. A malicious contract in the middle passes the check and steals funds.",
    fix: "Use msg.sender instead of tx.origin for permission checks.",
    confidence: "high",
    reference: SWC + "docs/SWC-115",
    pattern: /tx\.origin/,
    skipTests: false,
  },
  {
    id: "sol-selfdestruct",
    langs: ["solidity"],
    severity: "critical",
    category: "smart-contract",
    title: "selfdestruct in the contract",
    roast: "One wrong call and the whole contract vanishes. Funds included.",
    plain: "selfdestruct can delete the contract and send its balance away. If anyone can trigger it, your contract can be wiped.",
    fix: "Remove selfdestruct if you do not truly need it. If you do, lock it behind strong owner-only checks and consider a timelock.",
    confidence: "high",
    reference: SWC + "docs/SWC-106",
    pattern: /\bselfdestruct\s*\(|\bsuicide\s*\(/,
    skipTests: false,
  },
  {
    id: "sol-unchecked-call",
    langs: ["solidity"],
    severity: "critical",
    category: "smart-contract",
    title: "Low-level call result ignored",
    roast: "You sent the money and never checked if it arrived.",
    plain: "A low-level .call() returns whether it worked, but the result is being ignored. Failures pass silently and can break your logic.",
    fix: "Capture the result: (bool ok, ) = addr.call{value: amount}(''); require(ok, 'transfer failed');",
    confidence: "medium",
    reference: SWC + "docs/SWC-104",
    pattern: /\.call\{[^}]*\}\s*\(\s*["']{2}\s*\)\s*;/,
    skipTests: false,
  },
  {
    id: "sol-reentrancy",
    langs: ["solidity"],
    severity: "critical",
    category: "smart-contract",
    title: "Money sent before state is updated",
    roast: "This is the exact bug behind some of the biggest hacks in crypto.",
    plain: "Sending ETH with .call before updating balances lets an attacker call back in and drain funds (reentrancy).",
    fix: "Update your state first, then send money (checks-effects-interactions). Or use a reentrancy guard like OpenZeppelin's nonReentrant.",
    confidence: "low",
    reference: SWC + "docs/SWC-107",
    pattern: /\.call\{value:/,
    skipTests: false,
  },
  {
    id: "sol-delegatecall",
    langs: ["solidity"],
    severity: "critical",
    category: "smart-contract",
    title: "delegatecall to a variable address",
    roast: "delegatecall to an address you do not control is handing over the keys.",
    plain: "delegatecall runs another contract's code with your contract's storage. If the target can be set by someone else, they own your contract.",
    fix: "Only delegatecall to addresses you hard-code or tightly control. Validate the target and consider a proven proxy pattern.",
    confidence: "medium",
    reference: SWC + "docs/SWC-112",
    pattern: /\.delegatecall\s*\(/,
    skipTests: false,
  },
  {
    id: "sol-floating-pragma",
    langs: ["solidity"],
    severity: "medium",
    category: "smart-contract",
    title: "Floating compiler version",
    roast: "^0.8.0 means 'whatever compiler, surprise me'.",
    plain: "A pragma like ^0.8.0 lets the contract compile with many versions. A different version can change behavior in subtle ways.",
    fix: "Pin one version, for example: pragma solidity 0.8.24; so every build is the same.",
    confidence: "high",
    reference: SWC + "docs/SWC-103",
    pattern: /pragma\s+solidity\s+[\^>~]/,
    skipTests: false,
  },
  {
    id: "sol-timestamp-random",
    langs: ["solidity"],
    severity: "medium",
    category: "smart-contract",
    title: "block values used for randomness",
    roast: "Miners can nudge these numbers. Your 'random' is not random.",
    plain: "block.timestamp and blockhash can be influenced by whoever produces the block, so they are unsafe for lotteries or anything random.",
    fix: "Use a real randomness source like Chainlink VRF for anything where the result matters.",
    confidence: "low",
    reference: SWC + "docs/SWC-120",
    pattern: /block\.(timestamp|difficulty|prevrandao)|blockhash\s*\(/,
    skipTests: false,
  },
  {
    id: "sol-public-no-modifier",
    langs: ["solidity"],
    severity: "medium",
    category: "smart-contract",
    title: "Sensitive function may be unprotected",
    roast: "A public mint or withdraw with no guard is a free-for-all.",
    plain: "A function named like mint, withdraw, or setOwner looks public with no obvious access check. Anyone might be able to call it.",
    fix: "Add an access check such as onlyOwner, or OpenZeppelin AccessControl, to functions that move money or change ownership.",
    confidence: "low",
    reference: SWC + "docs/SWC-105",
    pattern: /function\s+(mint|withdraw|setOwner|transferOwnership|drain)\s*\([^)]*\)\s*(external|public)(?![^{]*(onlyOwner|require\s*\(|_checkRole|hasRole))/,
    skipTests: false,
  },
];
