import type { Rule } from "./types";

export const webRules: Rule[] = [
  {
    id: "js-eval",
    langs: ["js", "ts"],
    severity: "critical",
    category: "security",
    title: "eval() in the code",
    roast: "eval is how you turn a small bug into a full takeover.",
    plain: "eval() runs whatever string you give it as code. If any of that string comes from a user, they can run their own code.",
    fix: "Drop eval(). For JSON use JSON.parse(). For dynamic logic use a lookup object or a real function.",
    confidence: "medium",
    reference: "https://cwe.mitre.org/data/definitions/95.html",
    pattern: /(^|[^.\w])eval\s*\(/,
    skipTests: true,
  },
  {
    id: "js-dangerous-html",
    langs: ["js", "ts"],
    severity: "medium",
    category: "security",
    title: "dangerouslySetInnerHTML in use",
    roast: "The prop literally has 'dangerous' in the name. They warned you.",
    plain: "This injects raw HTML into the page. If the HTML comes from a user, they can run scripts in your app (XSS).",
    fix: "Render text as text. If you must allow HTML, clean it first with a library like DOMPurify.",
    confidence: "medium",
    reference: "https://owasp.org/www-community/attacks/xss/",
    pattern: /dangerouslySetInnerHTML/,
    skipTests: true,
  },
  {
    id: "js-sql-concat",
    langs: ["js", "ts"],
    severity: "critical",
    category: "security",
    title: "SQL built by gluing strings together",
    roast: "This is how the famous '; DROP TABLE happens.",
    plain: "A SQL query is built with string joining and user input. Attackers can rewrite the query (SQL injection).",
    fix: "Use parameters, not string joining. Example: db.query('SELECT * FROM users WHERE id = $1', [id]).",
    confidence: "medium",
    reference: "https://owasp.org/www-community/attacks/SQL_Injection",
    pattern: /(query|execute)\s*\(\s*[`"'][^`"']*(\$\{|["']\s*\+)/,
    skipTests: true,
  },
  {
    id: "js-cors-star",
    langs: ["js", "ts"],
    severity: "medium",
    category: "security",
    title: "CORS open to everyone",
    roast: "You invited the entire internet to your API. They came.",
    plain: "CORS is set to '*', so any website can call your API from a user's browser.",
    fix: "List only the sites you trust. Example: cors({ origin: ['https://yourapp.com'] }).",
    confidence: "high",
    reference: "https://developer.mozilla.org/docs/Web/HTTP/CORS",
    pattern: /(cors|Access-Control-Allow-Origin)[^"'\n]{0,40}["']\*["']/i,
    skipTests: true,
  },
  {
    id: "js-child-process",
    langs: ["js", "ts"],
    severity: "critical",
    category: "security",
    title: "Shell command built from input",
    roast: "Running user text as a shell command. What could go wrong, everything.",
    plain: "exec() runs a shell command. If part of that command is user input, they can run their own commands on your server.",
    fix: "Use execFile() with an argument array, never glue user input into the command string.",
    confidence: "low",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /exec\s*\(\s*[`"'][^`"']*(\$\{|["']\s*\+)/,
    skipTests: true,
  },
  {
    id: "js-jwt-none",
    langs: ["js", "ts"],
    severity: "critical",
    category: "auth",
    title: 'JWT "none" algorithm allowed',
    roast: "Accepting unsigned tokens is like checking IDs but accepting napkins.",
    plain: "Your token setup allows the 'none' algorithm, which means a token with no signature is accepted. Anyone can forge a login.",
    fix: "Pin the algorithm. Example: jwt.verify(token, secret, { algorithms: ['HS256'] }).",
    confidence: "medium",
    reference: "https://owasp.org/www-project-web-security-testing-guide/",
    pattern: /alg(orithm)?s?\s*[:=]\s*\[?\s*["']none["']/i,
    skipTests: true,
  },
];

export const pythonRules: Rule[] = [
  {
    id: "py-eval-exec",
    langs: ["python"],
    severity: "critical",
    category: "security",
    title: "eval() or exec() in Python",
    roast: "exec() is a loaded foot-gun with a hair trigger.",
    plain: "eval() and exec() run strings as code. With any user input, that is remote code execution.",
    fix: "Use ast.literal_eval() for data, or a dict lookup for choices. Avoid exec entirely.",
    confidence: "medium",
    reference: "https://cwe.mitre.org/data/definitions/95.html",
    pattern: /(^|[^.\w])(eval|exec)\s*\(/,
    skipTests: true,
  },
  {
    id: "py-subprocess-shell",
    langs: ["python"],
    severity: "critical",
    category: "security",
    title: "subprocess with shell=True",
    roast: "shell=True plus user input equals free server access for strangers.",
    plain: "Running a subprocess with shell=True and user input lets attackers run their own commands.",
    fix: "Pass a list of arguments and leave shell=False. Example: subprocess.run(['ls', path]).",
    confidence: "medium",
    reference: "https://cwe.mitre.org/data/definitions/78.html",
    pattern: /subprocess\.(run|call|Popen|check_output)\([^)]*shell\s*=\s*True/,
    skipTests: true,
  },
  {
    id: "py-pickle",
    langs: ["python"],
    severity: "medium",
    category: "security",
    title: "pickle.loads on outside data",
    roast: "pickle will happily unpack a bomb if you hand it one.",
    plain: "pickle can run code while loading. Never use it on data from users or the network.",
    fix: "Use json for data you did not create. Keep pickle for your own trusted files only.",
    confidence: "low",
    reference: "https://docs.python.org/3/library/pickle.html",
    pattern: /pickle\.loads?\s*\(/,
    skipTests: true,
  },
  {
    id: "py-yaml-load",
    langs: ["python"],
    severity: "medium",
    category: "security",
    title: "Unsafe yaml.load",
    roast: "Plain yaml.load can build any Python object. Including bad ones.",
    plain: "yaml.load without SafeLoader can run code from a crafted file.",
    fix: "Use yaml.safe_load() instead.",
    confidence: "medium",
    reference: "https://pyyaml.org/wiki/PyYAMLDocumentation",
    pattern: /yaml\.load\s*\((?![^)]*SafeLoader)/,
    skipTests: true,
  },
  {
    id: "py-flask-debug",
    langs: ["python"],
    severity: "medium",
    category: "security",
    title: "Flask debug mode on",
    roast: "Debug mode in production is a public Python shell. Cozy.",
    plain: "Running Flask with debug=True exposes an interactive debugger that can run code.",
    fix: "Set debug=False in production, or drive it from an env var.",
    confidence: "medium",
    reference: "https://flask.palletsprojects.com/en/latest/debugging/",
    pattern: /app\.run\([^)]*debug\s*=\s*True/,
    skipTests: true,
  },
];
